.\" manual page for w2html, a HTML exporter for w2do
.\" Copyright (C) 2008 Jaromir Hradilek
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.2 or
.\" any later version published by the Free Software Foundation;  with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" 
.\" A copy  of the license is included  as a file called FDL  in the main
.\" directory of the w2do source package.
.\"
.TH W2HTML 1 "15 September 2008" "Version 2.1.0"
.SH NAME
w2html \- a HTML exporter for w2do
.SH SYNOPSIS
.B  w2html
.RB [ \-B | \-D ]
.RB [ \-H
.IR heading ]
.RB [ \-o
.IR file ]
.RB [ \-s
.IR file ]
.RB [ \-f | \-u ]
.RB [ \-d
.IR date ]
.br
.RB "       [" \-g
.IR group ]
.RB [ \-p
.IR priority ]
.RB [ \-t
.IR task ]
.br
.B  w2html
.BR  \-h " | " \-v
.SH DESCRIPTION
.B w2html
is a HTML exporter for w2do, a simple to use yet efficient command-line
todo manager written in Perl 5. All tasks are listed by default, but
desired subset can be easily selected via specifying options.
.SH OPTIONS
.SS General options
.TP
.BR \-h ", " \-\-help
Display help message and exit.
.TP
.BR \-v ", " \-\-version
Display version information and exit.
.SS Specifying options
.TP
.BI \-t " task" "\fR,\fP \-\-task" " task"
Specify the
.I task
name.
.TP
.BI \-g " group" "\fR,\fP \-\-group" " group"
Specify the
.I group
name. The group name should be a single word with maximum of 10 characters,
but longer names are shortened automatically.
.TP
.BI \-d " date" "\fR,\fP \-\-date" " date"
Specify the due
.IR date .
Available options are
.BR anytime ", " today ", " yesterday ", " tomorrow ", " month ", "
.BR year ", "
or an exact date in the YYYY-MM-DD format, e.g. 2008-06-17 for 17 June
2008.
.TP
.BI \-p " priority" "\fR,\fP \-\-priority" " priority"
Specify the
.IR priority .
Available options are integers between
.BR 1 " and " 5 ,
where 1 represents the highest priority.
.TP
.BR \-f ", " \-\-finished
Specify the finished task.
.TP
.BR \-u ", " \-\-unfinished
Specify the unfinished task.
.SS Additional options
.TP
.BI \-o " file" "\fR,\fP \-\-output" " file"
Use selected
.I file
instead of the standard output.
.TP
.BI \-s " file" "\fR,\fP \-\-savefile" " file"
Use selected
.I file
instead of the default
.I ~/.w2do
as a save file.
.TP
.BI \-H " heading" "\fR,\fP \-\-heading" " heading"
Use selected
.IR heading .
.TP
.BR \-B ", " \-\-blue
Produce a HTML page with blue design; the default option.
.TP
.BR \-D ", " \-\-dark
Produce a HTML page with dark design.
.SH ENVIRONMENT
.TP
.B W2DO_SAVEFILE
Use selected file instead of the default
.I ~/.w2do
as a save file.
.SH FILES
.TP
.I ~/.w2do
Default save file.
.SH SEE ALSO
.BR w2do (1),
.BR w2text (1),
.BR perl (1).
.SH BUGS
To report bugs please visit the appropriate section on the project
homepage: <http://code.google.com/p/w2do/issues/>.
.SH AUTHOR
Written by Jaromir Hradilek <jhradilek@gmail.com>.
.PP
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.2 or any later
version published by the Free Software Foundation; with no Invariant
Sections, no Front-Cover Texts, and no Back-Cover Texts.
.PP
A copy of the license is included as a file called FDL in the main
directory of the w2do source package.
.SH COPYRIGHT
Copyright (C) 2008 Jaromir Hradilek
.PP
This program is free software; see the source for copying conditions. It is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
